/**  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
  useSidebar: [{type: 'autogenerated', dirName: 'use'}],
  mineSidebar: [{type: 'autogenerated', dirName: 'mine'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'build'}],
  exchangeSidebar: [{type: 'autogenerated', dirName: 'exchange'}]
 
};

export default sidebars;
