/**  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  learnSidebar: [{type: 'autogenerated', dirName: 'Learn'}],
  useSidebar: [{type: 'autogenerated', dirName: 'Use'}],
  mineSidebar: [{type: 'autogenerated', dirName: 'mine'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'Build'}],
  exchangeSidebar: [{type: 'autogenerated', dirName: 'Exchange'}]
 
};

export default sidebars;
